# docker compose file for spinning up backend services only with ports mapped to local host
# This is useful for running api on local system (outside of docker container) while accessing 
# dockerised backend services

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  4store:
    image: bde2020/4store
    #volume: fourstore:/var/lib/4store
    command: >
      bash -c "4s-backend-setup --segments 4 ontoportal_kb
      && 4s-backend ontoportal_kb
      && 4s-httpd -D -s-1 -p 9000 ontoportal_kb"
    ports:
      - "9000:9000"


  solr:
    image: ontoportal/solr-ut:0.1

  mgrep:
    image: ontoportal/mgrep-ncbo:0.1
    ports:
      - "55555:55556" #port 55555 is not avaiable on mac so we are using 55556

  agraph:
    image: franzinc/agraph:v7.3.1
    environment:
      - AGRAPH_SUPER_USER=test
      - AGRAPH_SUPER_PASSWORD=xyzzy
    shm_size: 1g
    ports:
      - 10035:10035
    command: >
       bash -c "/agraph/bin/agraph-control --config /agraph/etc/agraph.cfg start
       ; agtool repos create bioportal_test
       ; agtool users add anonymous
       ; agtool users grant anonymous root:bioportal_test:rw
       ; tail -f /agraph/data/agraph.log"
    profiles:
      - agraph

volumes:
  bundle:
 #fourstore:
